version: '3.8'
services:

  elasticsearch:
    image: 'elasticsearch:7.11.1'
    container_name: elasticsearch
    restart: unless-stopped
    privileged: true
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=cortex
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - '/misp-cortex/cortex/data:/usr/share/elasticsearch/data'
      - '/misp-cortex/cortex/logs:/usr/share/elasticsearch/logs'

  cortex:
    image: 'thehiveproject/cortex:3.1.6-1'
    container_name: cortex
    restart: unless-stopped
    ports:
    - 9001:9001
    volumes:
      - '/misp-cortex/cortex/application.conf:/etc/cortex/application.conf'
      - '/misp-cortex/cortex/cortex-jobs:/opt/cortex/jobs'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - elasticsearch